#!/usr/bin/python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import optparse
import os
import sys
from rmake.lib import chrootcache
from rmake.server import servercfg


def main():
    parser = optparse.OptionParser('%prog <hours> <dir>')
    parser.add_option('-t', '--test', action='store_true')
    parser.add_option('-v', '--verbose', action='store_true')
    options, args = parser.parse_args()
    if len(args) != 2:
        parser.print_usage()
        sys.exit("Expected two arguments")
    hours = int(args[0])
    path = args[1]
    helper = servercfg.rMakeBuilderConfiguration().getChrootHelper()
    cache = chrootcache.BtrfsChrootCache(os.path.abspath(path), helper)
    for fingerprint in cache.findOld(hours):
        if options.test or options.verbose:
            print 'Removing cached chroot', fingerprint.encode('hex')
        if not options.test:
            cache.remove(fingerprint)


if __name__ == '__main__':
    main()
