#!/bin/sh
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

bindir=$(dirname $0)
bin=$(basename $0)
importdir=$(cd $bindir/.. 2> /dev/null && pwd -P;)
export PYTHONPATH=$importdir:$CONARY_PATH
declare -a config
config=

if [ "$bin" = "rmake-server" ]; then
    # single-node local rmake server
    modes=$(stat -c '%a %u %g' $importdir/commands/chroothelper)
    if [ "$modes" != "4755 0 0" ]; then
        echo "run make test to make chroothelper setuid root"
        exit 1;
    fi
    certfile=/tmp/rmake-server-cert.pem
    # Force the generation of a new SSL certificate
    rm -f $certfile
    config=("--config=helperDir $importdir/commands"
            "--config=sslCertPath $certfile")

elif [ "$bin" = "rmake-node" ]; then
    # multi-node rmake worker
    modes=$(stat -c '%a %u %g' $importdir/commands/chroothelper)
    if [ "$modes" != "4755 0 0" ]; then
        echo "run make test to make chroothelper setuid root"
        exit 1;
    else
        config=("--config=helperDir $importdir/commands"
                )
    fi
fi

exec $importdir/commands/$bin "$@" ${config:+"${config[@]}"}
